// Generated by CoffeeScript 1.12.5
(function() {
  var $, ipcRenderer;

  $ = require('jquery');

  ipcRenderer = require('electron').ipcRenderer;

  $('#login').click(function() {
    return $.ajax({
      url: "http://elevisor.iptime.org:9937/api/v3/session",
      method: 'POST',
      data: {
        login: $('#gitlab_id').val(),
        password: $('#gitlab_passwd').val()
      }
    }).done(function(rslt) {
      ipcRenderer.sendSync('login', rslt.private_token);
      return window.location.replace('index.html');
    }).fail(function(dd) {
      return alert('login fail!');
    });
  });

}).call(this);

//# sourceMappingURL=login.js.map
